language: c

script:
  - wget http://shyboy.oss-cn-shenzhen.aliyuncs.com/readonly/tc32_gcc_v2.0.tar.bz2  && tar -xvjf tc32_gcc_v2.0.tar.bz2 -C /opt/
  - git clone https://github.com/Ai-Thinker-Open/Telink_825X_SDK
  - export PATH=$PATH:/opt/tc32/bin
  - make -j TEL_PATH=./Telink_825X_SDK 
  - ls ./out
  - ls

deploy:
  provider: releases
  api_key: $API_GITHUB
  file: 
  - ATC_Thermometer.bin
  skip_cleanup: true
