language: c

script:
  - wget http://shyboy.oss-cn-shenzhen.aliyuncs.com/readonly/tc32_gcc_v2.0.tar.bz2  && tar -xvjf tc32_gcc_v2.0.tar.bz2 -C /opt/ && export PATH=$PATH:/opt/tc32/bin
  - git clone https://github.com/Ai-Thinker-Open/Telink_825X_SDK .
  - ls
  - cd src
  - make
